# Generated by Django 5.0.7 on 2024-08-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('choice', models.CharField(max_length=100)),
                ('either', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.either')),
            ],
        ),
    ]
