# Generated by Django 5.0.7 on 2024-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=100),
        ),
    ]
